In [55]:
import numpy as np

In [56]:
A = np.array(([2,-1,0],[-1,2,-1],[0,-1,2]))
A

array([[ 2, -1,  0],
       [-1,  2, -1],
       [ 0, -1,  2]])

In [57]:
I = np.identity(A.shape[0])
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [58]:
AI = np.hstack([A,I])
AI

array([[ 2., -1.,  0.,  1.,  0.,  0.],
       [-1.,  2., -1.,  0.,  1.,  0.],
       [ 0., -1.,  2.,  0.,  0.,  1.]])

In [59]:
a10 = AI[1,0] / AI[0,0]
a10

-0.5

In [60]:
AI[1] = AI[1] - AI[0] * a10
AI[1]

array([ 0. ,  1.5, -1. ,  0.5,  1. ,  0. ])

In [61]:
a21 = AI[2,1] / AI[1,1]
a21

-0.6666666666666666

In [62]:
AI[2] = AI[2] - AI[1] * a21
AI[2]

array([0.        , 0.        , 1.33333333, 0.33333333, 0.66666667,
       1.        ])

In [63]:
AI

array([[ 2.        , -1.        ,  0.        ,  1.        ,  0.        ,
         0.        ],
       [ 0.        ,  1.5       , -1.        ,  0.5       ,  1.        ,
         0.        ],
       [ 0.        ,  0.        ,  1.33333333,  0.33333333,  0.66666667,
         1.        ]])

In [64]:
a12 = AI[1,2] / AI[2,2]
a12

-0.7499999999999999

In [65]:
AI[1] = AI[1] - AI[2] * a12
AI[1]

array([0.  , 1.5 , 0.  , 0.75, 1.5 , 0.75])

In [66]:
a11 = AI[0,1] / AI[1,1]
a11

-0.6666666666666666

In [67]:
AI[0] = AI[0] - AI[1] * a11
AI[0]

array([2. , 0. , 0. , 1.5, 1. , 0.5])

In [68]:
AI

array([[2.        , 0.        , 0.        , 1.5       , 1.        ,
        0.5       ],
       [0.        , 1.5       , 0.        , 0.75      , 1.5       ,
        0.75      ],
       [0.        , 0.        , 1.33333333, 0.33333333, 0.66666667,
        1.        ]])

In [69]:
AI[0] = AI[0] / AI[0,0]

In [70]:
AI[1] = AI[1] / AI[1,1]

In [71]:
AI[2] = AI[2] / AI[2,2]

In [72]:
AI

array([[1.  , 0.  , 0.  , 0.75, 0.5 , 0.25],
       [0.  , 1.  , 0.  , 0.5 , 1.  , 0.5 ],
       [0.  , 0.  , 1.  , 0.25, 0.5 , 0.75]])