In [1]:
import numpy as np

In [2]:
S = np.array(([2,1],[1,2]))
S

array([[2, 1],
       [1, 2]])

In [4]:
x1 = np.array(([1],[1]))
x1

array([[1],
       [1]])

In [6]:
S@x1

array([[3],
       [3]])

In [7]:
3*x1

array([[3],
       [3]])

In [8]:
A = np.array(([8,3],[2,7]))
A

array([[8, 3],
       [2, 7]])

In [9]:
import sympy

In [10]:
x = sympy.Symbol('x')

In [11]:
lamda = np.array(([x,0],[0,x]))
lamda

array([[x, 0],
       [0, x]], dtype=object)

In [23]:
det = (A - lamda).reshape(2,2)

In [24]:
det_lamda = det[0][0] * det[1][1] - det[0][1] * det[1][0]
det_lamda

(7 - x)*(8 - x) - 6