In [1]:
import numpy as np

In [2]:
import sympy

In [3]:
v1 = sympy.Symbol('v1')
v2 = sympy.Symbol('v2')

In [5]:
A = np.array(([2,3],[4,5]))
A

array([[2, 3],
       [4, 5]])

In [6]:
v = np.array(([v1],[v2]))
v

array([[v1],
       [v2]], dtype=object)

In [7]:
A.dot(v)

array([[2*v1 + 3*v2],
       [4*v1 + 5*v2]], dtype=object)

In [22]:
A[:,0]

array([2, 4])

In [21]:
A[:,0] * v1 + A[:,1] * v2

array([2*v1 + 3*v2, 4*v1 + 5*v2], dtype=object)