In [1]:
import numpy as np

In [3]:
A = np.array(([1,3,8],[1,2,6],[0,1,2]))
A

array([[1, 3, 8],
       [1, 2, 6],
       [0, 1, 2]])

In [22]:
for i in A[:,0]:
  if i != 0:
    C = A[:,0].reshape(A[:,0].shape[0],-1)
    break

In [23]:
C

array([[1],
       [1],
       [0]])

In [25]:
a = A[:,0] / A[:,1]
a_true = 1

for i in a:
  if a[0] == i:
    continue
  else:
    a_true = 0
    break

if a_true == 1:
  np.stack((C, A[:,1].reshape(A[:,1].shape[0],-1)))

In [26]:
C

array([[1],
       [1],
       [0]])

In [ ]:
for i in range(0, A.shape[1]):
  