In [10]:
import numpy as np

In [11]:
import sympy

In [8]:
A = np.array(([2,3],[2,4],[3,7]))

In [9]:
A

array([[2, 3],
       [2, 4],
       [3, 7]])

In [12]:
x1 = sympy.Symbol('x1')
x2 = sympy.Symbol('x2')

In [14]:
x = np.array(([x1],[x2]))

In [15]:
x

array([[x1],
       [x2]], dtype=object)

In [17]:
A.dot(x)

array([[2*x1 + 3*x2],
       [2*x1 + 4*x2],
       [3*x1 + 7*x2]], dtype=object)

In [27]:
A[:,0] * x[0]

array([2*x1, 2*x1, 3*x1], dtype=object)

In [28]:
A[:,1] * x[1]

array([3*x2, 4*x2, 7*x2], dtype=object)