In [1]:
import numpy as np

In [2]:
import sympy

In [5]:
A = np.array(([1,3,8],[1,2,6],[0,1,2]))

In [6]:
A

array([[1, 3, 8],
       [1, 2, 6],
       [0, 1, 2]])

In [8]:
a1 = A[:,0]
a1

array([1, 1, 0])

In [9]:
a2 = A[:,1]
a2

array([3, 2, 1])

In [10]:
a1/a2

array([0.33333333, 0.5       , 0.        ])

In [12]:
A[:,:2]

array([[1, 3],
       [1, 2],
       [0, 1]])

In [13]:
x1 = sympy.Symbol('x1')
x2 = sympy.Symbol('x2')

In [16]:
x = np.array(([x1],[x2]))

In [20]:
x

array([[x1],
       [x2]], dtype=object)

In [21]:
A[:,:2].dot(x)

array([[x1 + 3*x2],
       [x1 + 2*x2],
       [x2]], dtype=object)

In [23]:
A[:,:2].dot(x)[0][0]

x1 + 3*x2

In [25]:
A[:,:2].dot(x)[1][0]

x1 + 2*x2

In [26]:
A[:,:2].dot(x)[2][0]

x2