In [1]:
import numpy as np

In [2]:
import sympy

In [5]:
A = np.array(([2],[2],[1]))

In [10]:
A.shape

(3, 1)

In [12]:
B = np.array(([3, 4, 6])).reshape(1,-1)

In [13]:
B.shape

(1, 3)

In [14]:
A@B

array([[ 6,  8, 12],
       [ 6,  8, 12],
       [ 3,  4,  6]])

In [15]:
A.dot(B)

array([[ 6,  8, 12],
       [ 6,  8, 12],
       [ 3,  4,  6]])

In [16]:
A.dot(B).T

array([[ 6,  6,  3],
       [ 8,  8,  4],
       [12, 12,  6]])

In [17]:
B.T@A.T

array([[ 6,  6,  3],
       [ 8,  8,  4],
       [12, 12,  6]])