In [1]:
import numpy as np

In [2]:
A = np.array(([1,2,6],[0,0,5]))
A

array([[1, 2, 6],
       [0, 0, 5]])

In [4]:
AT = A.T
AT

array([[1, 0],
       [2, 0],
       [6, 5]])

In [5]:
B = np.array(([1,2],[3,4],[5,6]))
B

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
AB = A.dot(B)
AB

array([[37, 46],
       [25, 30]])

In [7]:
A.dot(B).T

array([[37, 25],
       [46, 30]])

In [8]:
B.T.dot(A.T)

array([[37, 25],
       [46, 30]])

In [11]:
np.linalg.inv(AB).T

array([[-0.75 ,  1.15 ],
       [ 0.625, -0.925]])

In [12]:
np.linalg.inv(AB.T)

array([[-0.75 ,  0.625],
       [ 1.15 , -0.925]])

In [14]:
A.dot(AT)

array([[41, 30],
       [30, 25]])

후방 차분 행렬

In [16]:
import sympy

In [17]:
v1 = sympy.Symbol('v1')
v2 = sympy.Symbol('v2')
v3 = sympy.Symbol('v3')

In [18]:
v = np.array(([v1],[v2],[v3]))
v

array([[v1],
       [v2],
       [v3]], dtype=object)

In [15]:
b_d_m_A = np.array(([1,0,0],[-1,1,0],[0,-1,1],[0,0,-1]))
b_d_m_A

array([[ 1,  0,  0],
       [-1,  1,  0],
       [ 0, -1,  1],
       [ 0,  0, -1]])

In [21]:
Av = b_d_m_A.dot(v)
Av

array([[v1],
       [-v1 + v2],
       [-v2 + v3],
       [-v3]], dtype=object)

In [22]:
AT = b_d_m_A.T
AT

array([[ 1, -1,  0,  0],
       [ 0,  1, -1,  0],
       [ 0,  0,  1, -1]])

In [24]:
w1 = sympy.Symbol('w1')
w2 = sympy.Symbol('w2')
w3 = sympy.Symbol('w3')
w4 = sympy.Symbol('w4')

In [25]:
w = np.array(([w1],[w2],[w3],[w4]))
w

array([[w1],
       [w2],
       [w3],
       [w4]], dtype=object)

In [26]:
AT.dot(w)

array([[w1 - w2],
       [w2 - w3],
       [w3 - w4]], dtype=object)

In [28]:
S = AT.dot(b_d_m_A)
S

array([[ 2, -1,  0],
       [-1,  2, -1],
       [ 0, -1,  2]])

In [29]:
S.dot(v)

array([[2*v1 - v2],
       [-v1 + 2*v2 - v3],
       [-v2 + 2*v3]], dtype=object)

In [31]:
L = b_d_m_A.dot(b_d_m_A.T)
L

array([[ 1, -1,  0,  0],
       [-1,  2, -1,  0],
       [ 0, -1,  2, -1],
       [ 0,  0, -1,  1]])

In [32]:
w = np.array(([1],[1],[1],[1]))
w

array([[1],
       [1],
       [1],
       [1]])

In [33]:
L.dot(w)

array([[0],
       [0],
       [0],
       [0]])