In [1]:
import numpy as np

In [40]:
A = np.array(([1,2,3],[2,5,7],[2,7,8]))
A

array([[1, 2, 3],
       [2, 5, 7],
       [2, 7, 8]])

In [3]:
L = np.zeros((3,3))
L

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [4]:
L2 = np.zeros((3,3))
L2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [48]:
L3 = np.zeros((3,3))
L3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
L4 = np.zeros((3,3))
L4

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
U = np.zeros((3,3))
U

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
L[0][0] = A[0][0] / 1

In [9]:
L[1][0] = A[1][0] / A[0][0]

In [10]:
L[2][0] = A[2][0] / A[0][0]

In [11]:
L

array([[1., 0., 0.],
       [2., 0., 0.],
       [2., 0., 0.]])

In [12]:
L2[0] = L[0][0] * A[0]

In [13]:
L2[1] = L[1][0] * A[0]

In [14]:
L2[2] = L[2][0] * A[0]

In [15]:
L2

array([[1., 2., 3.],
       [2., 4., 6.],
       [2., 4., 6.]])

In [41]:
A = A - L2
A

array([[ 0.,  0.,  0.],
       [ 0.,  1.,  1.],
       [ 0.,  3., 10.]])

In [42]:
L[1][1] = A[1][1] / 1

In [43]:
L[2][1] = A[2][1] / A[1][1]

In [44]:
L

array([[1., 0., 0.],
       [2., 1., 0.],
       [2., 3., 0.]])

In [49]:
L3[1][1:] = L[1][1] * A[1][1:]

In [50]:
L3[2][1:] = L[2][1] * A[1][1:]

In [51]:
L3

array([[0., 0., 0.],
       [0., 1., 1.],
       [0., 3., 3.]])

In [52]:
A = A - L3
A

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 7.]])

In [59]:
L[2][2] = A[2][2] / 7

In [60]:
L

array([[1., 0., 0.],
       [2., 1., 0.],
       [2., 3., 1.]])

In [61]:
L4 [2][2] = L[2][2] * A[2][2]

In [62]:
L4

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 7.]])