In [1]:
import numpy as np

In [2]:
A = np.array(([1,3,8],[1,2,6],[0,1,2]))
A

array([[1, 3, 8],
       [1, 2, 6],
       [0, 1, 2]])

In [3]:
for i in A[:,0]:
  if i != 0:
    C = A[:,0].reshape(A[:,0].shape[0],-1)
    break

In [4]:
C

array([[1],
       [1],
       [0]])

In [22]:
a = A[:,0] / A[:,1]
a_true = 0

for i in a:
  if a[0] == i:
    continue
  else:
    a_true = 1
    break

if a_true == 1:
  C = np.concatenate([C, A[:,1].reshape(A[:,1].shape[0],-1)], 1)

In [23]:
C

array([[1, 3],
       [1, 2],
       [0, 1]])

In [30]:
import sympy

In [31]:
x1 = sympy.symbols('x1')

In [41]:
X = []

for i in range(0, C.shape[1]):
  exec(f"x{i} = sympy.symbols('x{i}')")
  exec(f"X.append(x{i})")

In [45]:
X = np.array(X)
X

array([x0, x1], dtype=object)

In [50]:
C.dot(X.T).reshape(C.shape[0],-1)

array([[x0 + 3*x1],
       [x0 + 2*x1],
       [x1]], dtype=object)

In [53]:
C.dot(X.T).reshape(C.shape[0],-1) - A[:,2].reshape(A.shape[0],-1)

array([[x0 + 3*x1 - 8],
       [x0 + 2*x1 - 6],
       [x1 - 2]], dtype=object)