In [39]:
import numpy as np

In [40]:
import sympy

In [41]:
a1 = np.array(([1],[3]))

In [42]:
a1

array([[1],
       [3]])

In [43]:
a2 = np.array(([0],[1]))

In [44]:
a2

array([[0],
       [1]])

In [45]:
b1 = np.array(([2, 4])).reshape(1,-1)

In [46]:
b1

array([[2, 4]])

In [47]:
b2 = np.array(([0, 5])).reshape(1,-1)

In [48]:
b2

array([[0, 5]])

In [49]:
a1@b1

array([[ 2,  4],
       [ 6, 12]])

In [50]:
a2@b2

array([[0, 0],
       [0, 5]])

In [51]:
a1@b1+a2@b2

array([[ 2,  4],
       [ 6, 17]])

In [52]:
A = np.array(([1,0],[3,1]))

In [53]:
B = np.array(([2,4],[0,5]))

In [54]:
A@B

array([[ 2,  4],
       [ 6, 17]])