In [46]:
import numpy as np

In [47]:
A = np.array(([1,2,3,4],[6,7,8,9],[7,13,12,11],[13,17,4,3]))
A

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [ 7, 13, 12, 11],
       [13, 17,  4,  3]])

In [48]:
for i in range(1, A.shape[0]):
  A[i] = A[i] - (A[i][0] / A[0][0]) * A[0]

In [49]:
A

array([[  1,   2,   3,   4],
       [  0,  -5, -10, -15],
       [  0,  -1,  -9, -17],
       [  0,  -9, -35, -49]])

In [50]:
A = np.array(([1,2,3,4],[6,7,8,9],[7,13,12,11],[13,17,4,3]))
A

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [ 7, 13, 12, 11],
       [13, 17,  4,  3]])

In [51]:
for i in range(A.shape[0]-1):
  a = A[i][i]
  if(a == 0):
    continue
  for j in range(i+1, A.shape[0]):
    A[j] = A[j] - (A[j][i] / a) * A[i]

In [52]:
A

array([[  1,   2,   3,   4],
       [  0,  -5, -10, -15],
       [  0,   0,  -7, -14],
       [  0,   0,   0,  12]])