In [1]:
import numpy as np

In [2]:
A = np.array(([1,2],[3,6]))

In [3]:
A

array([[1, 2],
       [3, 6]])

In [4]:
C_A = np.array(([1],[3])).reshape(-1,1)

In [5]:
C_A

array([[1],
       [3]])

In [8]:
C_AT = np.array(([1],[2])).reshape(-1,1)

In [9]:
C_AT

array([[1],
       [2]])

In [10]:
N_A = np.array(([2],[-1])).reshape(-1,1)

In [11]:
N_A

array([[ 2],
       [-1]])

In [12]:
A@N_A

array([[0],
       [0]])

In [13]:
N_AT = np.array(([3],[-1])).reshape(-1,1)

In [14]:
N_AT

array([[ 3],
       [-1]])

In [15]:
A.T@N_AT

array([[0],
       [0]])