In [36]:
import numpy as np

In [56]:
A = np.array(([1,2,3,4],[6,7,8,9],[7,13,12,11],[13,17,4,3]))
A

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [ 7, 13, 12, 11],
       [13, 17,  4,  3]])

In [57]:
L = np.zeros((A.shape[0], A.shape[1]))
L

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [58]:
U = np.zeros((A.shape[0], A.shape[1]))
U[0] = A[0]
U

array([[1., 2., 3., 4.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [59]:
for i in range(A.shape[0]-1):
  a = A[i][i]
  if(a == 0):
    continue
  for j in range(i+1, A.shape[0]):
    L[j][i] = (A[j][i] / a)
    A[j] = A[j] - (A[j][i] / a) * A[i]
    U[j] = A[j]

In [60]:
for i in range(A.shape[0]):
  L[i][i] = 1

In [61]:
L

array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 6.        ,  1.        ,  0.        ,  0.        ],
       [ 7.        ,  0.2       ,  1.        ,  0.        ],
       [13.        ,  1.8       ,  2.42857143,  1.        ]])

In [62]:
U

array([[  1.,   2.,   3.,   4.],
       [  0.,  -5., -10., -15.],
       [  0.,   0.,  -7., -14.],
       [  0.,   0.,   0.,  12.]])

In [63]:
L.dot(U)

array([[ 1.,  2.,  3.,  4.],
       [ 6.,  7.,  8.,  9.],
       [ 7., 13., 12., 11.],
       [13., 17.,  4.,  3.]])

In [4]:
A

array([[  1,   2,   3,   4],
       [  0,  -5, -10, -15],
       [  0,   0,  -7, -14],
       [  0,   0,   0,  12]])

In [5]:
A = np.array(([1,2,3,4],[6,7,8,9],[7,13,12,11],[13,17,4,3]))
A

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [ 7, 13, 12, 11],
       [13, 17,  4,  3]])

In [6]:
for i in range(A.shape[0]):
  exec(f"l{i}u{i} = []")
  a = A[i][i]
  exec(f"l{i}u{i}.append(A[i])")
  for j in range(i+1, A.shape[0]):
    exec(f"l{i}u{i}.append((A[j][i] / a) * A[i])")
    A[j] = A[j] - (A[j][i] / a) * A[i]

In [7]:
list_a = []

for i in range(A.shape[0]):
  a = []
  for j in range(A.shape[0]-i):
    for k in range(A.shape[1]):
      exec(f"a.append(l{i}u{i}[j][k])")
  list_a.append(a)

In [8]:
len(list_a)

4

In [9]:
for i in range(len(list_a)):
  exec(f"l{i}u{i} = list_a[i]")
  exec(f"l{i}u{i} = np.array(l{i}u{i}).reshape(len(list_a)-i,-1)")
  if i != 0:
    exec(f"l{i}u{i} = np.concatenate((np.zeros((i,4)), l{i}u{i}))")

In [10]:
l0u0

array([[ 1.,  2.,  3.,  4.],
       [ 6., 12., 18., 24.],
       [ 7., 14., 21., 28.],
       [13., 26., 39., 52.]])

In [11]:
l1u1

array([[  0.,   0.,   0.,   0.],
       [  0.,  -5., -10., -15.],
       [  0.,  -1.,  -2.,  -3.],
       [  0.,  -9., -18., -27.]])

In [12]:
l2u2

array([[  0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.],
       [  0.,   0.,  -7., -14.],
       [  0.,   0., -17., -34.]])

In [13]:
l3u3

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0., 12.]])

In [14]:
new_A = np.zeros((4,4))
for i in range(len(list_a)):
  exec(f"new_A = new_A + l{i}u{i}")

In [15]:
new_A

array([[ 1.,  2.,  3.,  4.],
       [ 6.,  7.,  8.,  9.],
       [ 7., 13., 12., 11.],
       [13., 17.,  4.,  3.]])

In [16]:
A

array([[  1,   2,   3,   4],
       [  0,  -5, -10, -15],
       [  0,   0,  -7, -14],
       [  0,   0,   0,  12]])